source 'http://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.1.0'
gem 'mysql2'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc
gem 'spring',        group: :development

# Added Gems
gem 'rails_admin'
gem 'omniauth-facebook'
gem "less-rails"
gem 'therubyracer'
gem "twitter-bootstrap-rails"
gem 'acts_as_shopping_cart', '~> 0.2.1'
gem 'devise'
gem 'bootstrap-wysihtml5-rails', '0.3.1.24'
gem "paperclip", "~> 4.2"